# Generated by Django 5.2.17 on 2026-08-14 16:03

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


BASE_ITEMS = (
    ("食材物料", "Ingredients and Materials", "MATERIALS"),
    ("会计", "Accounting", "ACCOUNTING"),
    ("清洁费用", "Cleaning", "CLEANING"),
    ("保险", "Insurance", "INSURANCE"),
    ("店铺房租", "Shop Rent", "RENT"),
    ("电费", "Electricity", "UTILITIES"),
    ("燃气费", "Gas", "UTILITIES"),
    ("水费", "Water", "UTILITIES"),
    ("水电", "Utilities", "UTILITIES"),
    ("垃圾处理", "Waste Disposal", "WASTE"),
)


def snapshot_costs_and_update_templates(apps, schema_editor):
    CostItem = apps.get_model("costs", "CostItem")
    MonthlyCost = apps.get_model("costs", "MonthlyCost")

    for cost in MonthlyCost.objects.select_related("cost_item").all().iterator():
        if cost.cost_item_id:
            cost.name_zh = cost.cost_item.name_zh
            cost.name_en = cost.cost_item.name_en
            cost.category = cost.cost_item.category
            cost.save(update_fields=("name_zh", "name_en", "category"))

    CostItem.objects.update(is_active=False)
    for name_zh, name_en, category in BASE_ITEMS:
        item = CostItem.objects.filter(name_en=name_en).first()
        if item is None:
            item = CostItem.objects.filter(name_zh=name_zh).first()
        if item is None:
            CostItem.objects.create(
                name_zh=name_zh,
                name_en=name_en,
                category=category,
                is_active=True,
            )
        else:
            item.name_zh = name_zh
            item.name_en = name_en
            item.category = category
            item.is_active = True
            item.save(update_fields=("name_zh", "name_en", "category", "is_active"))


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0002_monthlycost_cost_month'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CostMonth',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month', models.DateField(unique=True)),
            ],
            options={
                'ordering': ('-month',),
            },
        ),
        migrations.AlterModelOptions(
            name='monthlycost',
            options={'ordering': ('incurred_date', 'name_en')},
        ),
        migrations.AddField(
            model_name='monthlycost',
            name='category',
            field=models.CharField(choices=[('RENT', 'Rent'), ('UTILITIES', 'Utilities'), ('INSURANCE', 'Insurance'), ('SOFTWARE', 'Software'), ('MAINTENANCE', 'Maintenance'), ('CLEANING', 'Cleaning'), ('ACCOUNTING', 'Accounting'), ('EQUIPMENT_RENTAL', 'Equipment rental'), ('WASTE', 'Waste disposal'), ('MATERIALS', 'Ingredients and materials'), ('OTHER', 'Other')], default='OTHER', max_length=24),
        ),
        migrations.AddField(
            model_name='monthlycost',
            name='name_en',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='monthlycost',
            name='name_zh',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='costitem',
            name='category',
            field=models.CharField(choices=[('RENT', 'Rent'), ('UTILITIES', 'Utilities'), ('INSURANCE', 'Insurance'), ('SOFTWARE', 'Software'), ('MAINTENANCE', 'Maintenance'), ('CLEANING', 'Cleaning'), ('ACCOUNTING', 'Accounting'), ('EQUIPMENT_RENTAL', 'Equipment rental'), ('WASTE', 'Waste disposal'), ('MATERIALS', 'Ingredients and materials'), ('OTHER', 'Other')], max_length=24),
        ),
        migrations.AlterField(
            model_name='monthlycost',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='monthlycost',
            name='cost_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthly_costs', to='costs.costitem'),
        ),
        migrations.RunPython(snapshot_costs_and_update_templates, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='monthlycost',
            constraint=models.UniqueConstraint(fields=('cost_month', 'name_zh'), name='unique_monthly_cost_name_zh'),
        ),
        migrations.AddConstraint(
            model_name='monthlycost',
            constraint=models.UniqueConstraint(fields=('cost_month', 'name_en'), name='unique_monthly_cost_name_en'),
        ),
    ]
