# Generated by Django 5.2.17 on 2026-08-14 13:38

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0004_normalize_generated_english_names'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=80, unique=True)),
                ('name_zh', models.CharField(max_length=160)),
                ('name_en', models.CharField(max_length=160)),
                ('holiday_date', models.DateField(db_index=True)),
                ('region', models.CharField(default='England and Wales', max_length=40)),
                ('notes', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ('holiday_date', 'name_en'),
            },
        ),
        migrations.CreateModel(
            name='BusinessEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180)),
                ('event_type', models.CharField(choices=[('PROMOTION', 'Promotion'), ('KOL_COLLABORATION', 'KOL collaboration'), ('CUSTOMER_LOYALTY', 'Customer loyalty'), ('PRODUCT_LAUNCH', 'Product launch'), ('MEMBER_EVENT', 'Member event'), ('MARKETING', 'Advertising and marketing'), ('SPECIAL_ORDER', 'Special order'), ('OFFLINE_PARTNERSHIP', 'Offline partnership'), ('OTHER', 'Other')], max_length=32)),
                ('start_date', models.DateField(db_index=True)),
                ('end_date', models.DateField(db_index=True)),
                ('preparation_days', models.PositiveSmallIntegerField(default=14)),
                ('expected_impact', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=12)),
                ('expected_sales_change', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('-100')), django.core.validators.MaxValueValidator(Decimal('999.99'))])),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('currency', models.CharField(default='GBP', max_length=3)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_events_created', to=settings.AUTH_USER_MODEL)),
                ('focus_products', models.ManyToManyField(blank=True, related_name='business_events', to='products.product')),
                ('linked_holiday', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_events', to='events.holiday')),
            ],
            options={
                'ordering': ('start_date', 'name'),
                'permissions': (('manage_events', 'Can manage events and business calendar'),),
            },
        ),
        migrations.CreateModel(
            name='BusinessClosure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180)),
                ('closure_type', models.CharField(choices=[('REST_DAY', 'Rest day'), ('TEMPORARY_CLOSURE', 'Temporary closure'), ('STAFF_LEAVE', 'Staff leave'), ('MAINTENANCE', 'Equipment maintenance'), ('RENOVATION', 'Renovation'), ('OTHER', 'Other')], max_length=24)),
                ('start_date', models.DateField(db_index=True)),
                ('end_date', models.DateField(db_index=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_closures_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('start_date', 'name'),
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='closure_end_on_or_after_start')],
            },
        ),
        migrations.CreateModel(
            name='EventChecklistItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('PRODUCT_PRODUCTION', 'Products and production'), ('INVENTORY_PURCHASING', 'Inventory and purchasing'), ('STORE_OPERATIONS', 'Store operations'), ('MARKETING', 'Marketing')], max_length=32)),
                ('title_zh', models.CharField(max_length=180)),
                ('title_en', models.CharField(max_length=180)),
                ('is_completed', models.BooleanField(default=False)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='events.businessevent')),
            ],
            options={
                'ordering': ('category', 'position', 'created_at'),
                'constraints': [models.UniqueConstraint(fields=('event', 'category', 'position'), name='unique_event_checklist_position')],
            },
        ),
        migrations.AddConstraint(
            model_name='businessevent',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='event_end_on_or_after_start'),
        ),
    ]
