# Generated by Django 5.2.17 on 2026-08-22 18:27

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('products', '0004_normalize_generated_english_names'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=60, unique=True)),
                ('name_zh', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('colour', models.CharField(default='blue', max_length=20)),
                ('icon_key', models.CharField(blank=True, max_length=40)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('position', 'name_en'),
            },
        ),
        migrations.CreateModel(
            name='ActivityPlatform',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=60, unique=True)),
                ('name_zh', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='platforms', to='events.activitycategory')),
            ],
            options={
                'ordering': ('category__position', 'position', 'name_en'),
            },
        ),
        migrations.CreateModel(
            name='ActivityPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=12)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('ENDED', 'Ended')], db_index=True, default='ACTIVE', max_length=12)),
                ('start_date', models.DateField(db_index=True)),
                ('end_date', models.DateField(blank=True, db_index=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activity_plans', to='events.activitycategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_plans_created', to=settings.AUTH_USER_MODEL)),
                ('focus_products', models.ManyToManyField(blank=True, related_name='activity_plans', to='products.product')),
                ('linked_business_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_plans', to='events.businessevent')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_activity_plans', to=settings.AUTH_USER_MODEL)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activity_plans', to='events.activityplatform')),
            ],
            options={
                'ordering': ('status', 'name'),
                'permissions': (('manage_activity_plans', 'Can manage activity plans and reminders'),),
            },
        ),
        migrations.CreateModel(
            name='ActivityReminderRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('frequency', models.CharField(choices=[('ONCE', 'Once'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], max_length=12)),
                ('interval', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(52)])),
                ('weekdays', models.JSONField(blank=True, default=list)),
                ('month_days', models.JSONField(blank=True, default=list)),
                ('reminder_time', models.TimeField()),
                ('timezone', models.CharField(default='Europe/London', max_length=64)),
                ('is_enabled', models.BooleanField(default=True)),
                ('plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_rule', to='events.activityplan')),
            ],
            options={
                'ordering': ('plan__name',),
            },
        ),
        migrations.CreateModel(
            name='ActivityReminderOccurrence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheduled_at', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('SKIPPED', 'Skipped'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=12)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('execution_notes', models.TextField(blank=True)),
                ('result_url', models.URLField(blank=True)),
                ('snoozed_until', models.DateTimeField(blank=True, null=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_activity_reminders', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='events.activityplan')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='events.activityreminderrule')),
            ],
            options={
                'ordering': ('scheduled_at', 'plan__name'),
            },
        ),
        migrations.AddConstraint(
            model_name='activityplan',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='activity_plan_end_on_or_after_start'),
        ),
        migrations.AddConstraint(
            model_name='activityreminderoccurrence',
            constraint=models.UniqueConstraint(fields=('rule', 'scheduled_at'), name='unique_activity_rule_occurrence'),
        ),
    ]
