# Generated by Django 5.2.17 on 2026-08-13 20:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_name', models.CharField(max_length=120)),
                ('work_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('work_content', models.CharField(blank=True, max_length=500)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_entries_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_entries_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('work_date', 'start_time', 'employee_name'),
                'permissions': (('manage_schedules', 'Can manage staff schedules'),),
                'indexes': [models.Index(fields=['work_date', 'start_time'], name='schedule_date_time_idx'), models.Index(fields=['employee_name', 'work_date'], name='schedule_employee_date_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='schedule_end_after_start')],
            },
        ),
    ]
