# Generated by Django 5.2.17 on 2026-08-13 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'permissions': (('manage_products', 'Can manage products and recipes'),)},
        ),
    ]
