# Generated by Django 5.2.17 on 2026-08-22 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_alter_auditlog_options_alter_accesslog_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesslog',
            name='system_mode',
            field=models.CharField(choices=[('TEST', 'Test'), ('PRODUCTION', 'Production'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=12),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='system_mode',
            field=models.CharField(choices=[('TEST', 'Test'), ('PRODUCTION', 'Production'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=12),
        ),
    ]
