# Generated by Django 5.2.17 on 2026-08-13 16:25

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationMenu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=64, unique=True, validators=[django.core.validators.RegexValidator(message='Use lowercase letters, numbers and single hyphens only.', regex='^[a-z0-9]+(?:-[a-z0-9]+)*$')])),
                ('name_zh', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='navigation_menus_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='navigation_menus_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name_en', 'code'),
                'permissions': (('manage_navigation', 'Can manage navigation menus'),),
            },
        ),
        migrations.CreateModel(
            name='NavigationItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_type', models.CharField(choices=[('CATEGORY', 'Category'), ('PAGE', 'Page')], max_length=16)),
                ('key', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Use lowercase letters, numbers, dots, underscores or hyphens only.', regex='^[a-z0-9]+(?:[._-][a-z0-9]+)*$')])),
                ('label_zh', models.CharField(max_length=100)),
                ('label_en', models.CharField(max_length=100)),
                ('icon_key', models.CharField(blank=True, max_length=64)),
                ('frontend_path', models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='Enter an internal path beginning with / and without a query string or fragment.', regex='^/(?:[A-Za-z0-9_-]+(?:/[A-Za-z0-9_-]+)*)?/?$')])),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='navigation_items_created', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='navigation.navigationitem')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='navigation_items_updated', to=settings.AUTH_USER_MODEL)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='navigation.navigationmenu')),
            ],
            options={
                'ordering': ('position', 'created_at'),
                'indexes': [models.Index(fields=['menu', 'parent', 'position'], name='nav_item_tree_order_idx'), models.Index(fields=['menu', 'is_active', 'is_visible'], name='nav_item_state_idx')],
                'constraints': [models.UniqueConstraint(fields=('menu', 'key'), name='unique_navigation_item_key_per_menu'), models.UniqueConstraint(condition=models.Q(('frontend_path__isnull', False)), fields=('menu', 'frontend_path'), name='unique_navigation_path_per_menu'), models.UniqueConstraint(condition=models.Q(('parent__isnull', True)), fields=('menu', 'position'), name='unique_top_level_navigation_position'), models.UniqueConstraint(condition=models.Q(('parent__isnull', False)), fields=('parent', 'position'), name='unique_child_navigation_position'), models.CheckConstraint(condition=models.Q(models.Q(('frontend_path__isnull', True), ('item_type', 'CATEGORY'), ('parent__isnull', True)), models.Q(('frontend_path__isnull', False), ('item_type', 'PAGE')), _connector='OR'), name='valid_navigation_item_shape')],
            },
        ),
    ]
