# Generated by Django 5.2.17 on 2026-08-13 21:05

import django.core.validators
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_number', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('gender', models.CharField(choices=[('UNSPECIFIED', 'Unspecified'), ('FEMALE', 'Female'), ('MALE', 'Male'), ('OTHER', 'Other')], default='UNSPECIFIED', max_length=16)),
                ('date_of_birth', models.DateField()),
                ('position', models.CharField(max_length=120)),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('employment_type', models.CharField(choices=[('FULL_TIME', 'Full time'), ('PART_TIME', 'Part time')], max_length=16)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ON_LEAVE', 'On leave'), ('DEPARTED', 'Departed'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=16)),
            ],
            options={
                'ordering': ('employee_number',),
                'permissions': (('manage_employees', 'Can manage bakery employees'),),
                'indexes': [models.Index(fields=['status', 'employee_number'], name='employee_status_number_idx')],
            },
        ),
    ]
