# Generated by Django 5.2.17 on 2026-08-14 16:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='departure_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
