# Generated by Django 5.2.17 on 2026-08-13 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_roles_username_and_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_protected',
            field=models.BooleanField(default=False),
        ),
    ]
