# Generated by Django 5.2.17 on 2026-08-13

import uuid

import django.db.models.deletion
from django.db import migrations, models


def create_preferences_for_existing_users(apps, schema_editor):  # type: ignore[no-untyped-def]
    User = apps.get_model("users", "User")
    UserPreference = apps.get_model("users", "UserPreference")
    UserPreference.objects.bulk_create(
        UserPreference(user_id=user_id) for user_id in User.objects.values_list("id", flat=True)
    )


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_is_protected"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPreference",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("theme", models.CharField(choices=[("light", "Light"), ("dark", "Dark"), ("bakery", "Bakery"), ("pink", "Princess Pink")], default="light", max_length=20)),
                ("locale", models.CharField(choices=[("zh-CN", "Chinese (Simplified)"), ("en-GB", "English (United Kingdom)")], default="zh-CN", max_length=10)),
                ("timezone", models.CharField(default="Europe/London", max_length=64)),
                ("date_format", models.CharField(default="DD/MM/YYYY", max_length=24)),
                ("week_starts_on", models.PositiveSmallIntegerField(default=1)),
                ("table_page_size", models.PositiveSmallIntegerField(default=10)),
                ("notification_settings", models.JSONField(blank=True, default=dict)),
                ("contract_interaction_settings", models.JSONField(blank=True, default=dict)),
                ("extra_settings", models.JSONField(blank=True, default=dict)),
                ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="preferences", to="users.user")),
            ],
            options={"ordering": ("user__username",)},
        ),
        migrations.RunPython(create_preferences_for_existing_users, migrations.RunPython.noop),
    ]
