# Generated by Django 5.2.17 on 2026-08-14 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_email_authentication_and_duplicate_usernames'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='sidebar_pinned',
            field=models.BooleanField(default=True),
        ),
    ]
