# Generated by Django 5.2.17 on 2026-08-14 12:18

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0004_normalize_generated_english_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('safety_buffer_days', models.PositiveSmallIntegerField(default=2)),
                ('ingredient', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_item', to='products.ingredient')),
            ],
            options={
                'ordering': ('ingredient__name',),
                'permissions': (('manage_inventory', 'Can manage inventory and production demand'),),
            },
        ),
        migrations.CreateModel(
            name='ProductionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(max_length=80, unique=True)),
                ('planned_date', models.DateField(db_index=True)),
                ('quantity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='PLANNED', max_length=16)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_plans', to='products.product')),
            ],
            options={
                'ordering': ('planned_date', 'product__name_zh'),
                'indexes': [models.Index(fields=['status', 'planned_date'], name='production_plan_window_idx')],
            },
        ),
    ]
