# Generated by Django 5.2.17 on 2026-08-14 12:45

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_purchaserequest'),
        ('products', '0004_normalize_generated_english_names'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(max_length=80, unique=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('unit', models.CharField(max_length=24)),
                ('base_quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('base_unit', models.CharField(max_length=24)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('price_unit', models.CharField(blank=True, max_length=24)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_receipts_created', to=settings.AUTH_USER_MODEL)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_receipts', to='products.ingredient')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_receipts', to='suppliers.supplier')),
            ],
            options={
                'ordering': ('-received_at', '-created_at'),
                'indexes': [models.Index(fields=['ingredient', 'received_at'], name='inventory_receipt_item_idx')],
            },
        ),
    ]
