# Generated by Django 5.2.17 on 2026-08-14 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventoryreceipt'),
        ('products', '0004_normalize_generated_english_names'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productionplan',
            options={'ordering': ('planned_date', 'product__name_zh'), 'permissions': (('manage_production_plans', 'Can manage production plans'),)},
        ),
        migrations.AddField(
            model_name='productionplan',
            name='actual_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='productionplan',
            constraint=models.UniqueConstraint(fields=('planned_date', 'product'), name='unique_production_plan_product_date'),
        ),
    ]
