# Generated by Django 5.2.17 on 2026-08-22 10:54

from django.db import migrations, models

import bakeops.inventory.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_productionplan_actual_cost_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryreceipt',
            name='invoice',
            field=models.FileField(blank=True, upload_to=bakeops.inventory.models.receipt_invoice_upload_to),
        ),
        migrations.AddField(
            model_name='inventoryreceipt',
            name='invoice_content_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='inventoryreceipt',
            name='invoice_original_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
